version: "3.9"
services:
  node1:
    container_name: node1
    hostname: node1
    environment:
      - NODES=node2:1323 node3:1323
    build: .
    ports:
      - "5001:1323"
    networks:
      - blockchain
  node2:
    container_name: node2
    hostname: node2
    environment:
      - NODES=node1:1323 node3:1323
    build: .
    ports:
      - "5002:1323"
    networks:
      - blockchain
  node3:
    container_name: node3
    hostname: node3
    environment:
      - NODES=node1:1323 node2:1323
    build: .
    ports:
      - "5003:1323"
    networks:
      - blockchain

networks:
  blockchain:
    driver: bridge
